### ISSUE TITLE
Potential use of prototype and builder design pattern on this beautiful package.

### ISSUE THREAD

**Issue by yukavirya** [nnieru/react-observable-network-helper#1]
while this package has been helping me with repetitive issue, but could we use some design pattern like prototype and builder?
in this case we could use prototype to clone the RequestFactory. (e.g: all the configuration is same, only url and mapper have different value), then we use the builder design pattern to set only the different value.

``` typescript
const requestGetPost = RequestFactory<PostModel[]>({
  url: "/posts",
  mapper: (data) => mapToPostModel(data),
  httpMethod: HttpMethod.GET,
  config: axiosConfig,
  onErrorAction: (err) => {
    console.error(err);
  },
});

const requestGetPostDetail = requestGetPost.clone();
requestGetPostDetail = requestGetPostDetail.setUrl("/posts-detail")....build();
```

let me know your thought about this. thanks!

**Comment by nnieru** [comment]
Hi @yukavirya thank you for your question. 

I think cloning the request factory is a good idea if the response expect to be identical. However, for now, a practical approach would be to separate the request values, as shown in the code below:

```typescript
  let request: RequestFactoryRequest<PostModel[]> = {
    url: "/posts",
    mapper: (data) => mapToPostModel(data),
    httpMetod: HttpMethod.GET,
    config: axiosConfig,
    onErrorAction: (err) => {
      console.log(err);
    },
  };

  const requestGetPost = RequestFactory<PostModel[]>(request);
  const requestGetDetail = RequestFactory<PostModel[]>({...request, url: '/post-detail'}); // the clone request
  const postRequestDetail = useObservableHttpClient(requestGetDetail);
```

However, when cloning a request, make sure that the **<T> data type** and the **axiosConfig** remain consistent across different requests. Inconsistencies in these parameters could cause unexpected behavior.

Have a nice day! ^^

**Comment by yukavirya** [comment]
okey Nierru, thankyou!
